### ISSUE TITLE
Port 80 already bound

### ISSUE THREAD

**Issue by MuffinmanGG** [DjCrqss/Woot-verlay#1]
Please allow users to reassign the port the application uses. Port 80 is a common port for many things.

**Comment by Starttoaster** [comment]
This is also causing me issues. Would like to get this sorted out, but I won't be closing my other applications to run this one. Port 80 is just too often taken, which is why most people write server apps to use a configurable port or use one from the ephemeral port range (30000-32767.)

**Comment by DjCrqss** [comment]
Sorry I'll look into this. I wanted an easy solution that runs for most users but port configuration would be a good idea.

**Comment by DjCrqss** [comment]
I haven't added port configuration yet as I am quite busy unfortunately, but I have changed the port to a value 32312 which nothing would probably use :)
