### ISSUE TITLE
Does not show any key input 60HE

### ISSUE THREAD

**Issue by MrEnder0** [DjCrqss/Woot-verlay#4]
Hello I have tried to use this with my 60HE but cant seem to make it show the key presses I have tried digital and analog profiles and Firefox and chrome but nothing works I have even tried the local file is there something i'm missing to get this working?

**Comment by DjCrqss** [comment]
Hey, have you downloaded the exe and made sure its running in the system tray?

**Comment by DjCrqss** [comment]
Closing if issue is stale :)
