### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by YAUIO** [DjCrqss/Woot-verlay#6]
is it possible to run it natively on Linux? Will be thankful for answer
![image](https://github.com/DjCrqss/Woot-verlay/assets/96724990/2706da08-8ae3-409b-b862-af9801dd4c6a)

**Comment by DjCrqss** [comment]
Hi there, it should be runnable on Linux if editing the source code. I originally only planned to make it run on Windows and used items such as Windows tray to store the running app. I'm a little busy right now but I may look into Linux support this summer :)

**Comment by DjCrqss** [comment]
With a quick look into the problem, since my program uses WindowsForms, you would have to remove or replace these with a Linux equivalent, and I had a look into keyboard event listeners but they are quite different since Linux has many different versions. If you would like to try it yourself, first try opening the .sln file and changing the target OS and disabling the Windows Forms check. Since I don't run any Linux on any of my devices it might be quite hard for me to test this sorry :( Happy to help you with it though

**Comment by YAUIO** [comment]
> With a quick look into the problem, since my program uses WindowsForms, you would have to remove or replace these with a Linux equivalent, and I had a look into keyboard event listeners but they are quite different since Linux has many different versions. If you would like to try it yourself, first try opening the .sln file and changing the target OS and disabling the Windows Forms check. Since I don't run any Linux on any of my devices it might be quite hard for me to test this sorry :( Happy to help you with it though

thank you! might look into it on the weekend

**Comment by YAUIO** [comment]
> With a quick look into the problem, since my program uses WindowsForms, you would have to remove or replace these with a Linux equivalent, and I had a look into keyboard event listeners but they are quite different since Linux has many different versions. If you would like to try it yourself, first try opening the .sln file and changing the target OS and disabling the Windows Forms check. Since I don't run any Linux on any of my devices it might be quite hard for me to test this sorry :( Happy to help you with it though

![image](https://github.com/DjCrqss/Woot-verlay/assets/96724990/061b7468-6677-4309-9cdd-c2ee423bfa38)

**Comment by DjCrqss** [comment]
Yeahh the windows forms should be able to be removed safely and run as a console app as you were doing. Finding a replacement for NeatInput's keyboard listener will be a bit harder. If we find a suitable replacement I'll try write one without the Windows Forms :)

**Comment by YAUIO** [comment]
> Yeahh the windows forms should be able to be removed safely and run as a console app as you were doing. Finding a replacement for NeatInput's keyboard listener will be a bit harder. If we find a suitable replacement I'll try write one without the Windows Forms :)

idk what you are exactly searching for, but maybe this will help https://wiki.archlinux.org/title/Keyboard_input
if you know some features of listener you need i will search for the exact replacement, just reply them to me

**Comment by DjCrqss** [comment]
I will try these next week hopefully but leaving them here for future reference
- https://www.nuget.org/packages/SharpHook.Reactive 
- https://www.nuget.org/packages/SharpHook/5.1.1#readme-body-tab

The reason why I didn't look into this earlier is because there is not much linux support, for example, the ones I am looking at for solutions seem to give up when it comes to linux:
- https://github.com/LegendaryB/NeatInput (What I currently use)
- https://github.com/Kir-Antipov/GlobalHook

If this sharp hook works I might be able to make it more compatible across platforms

**Comment by YAUIO** [comment]
> I will try these next week hopefully but leaving them here for future reference
> 
> * https://www.nuget.org/packages/SharpHook.Reactive
> * https://www.nuget.org/packages/SharpHook/5.1.1#readme-body-tab
> 
> The reason why I didn't look into this earlier is because there is not much linux support, for example, the ones I am looking at for solutions seem to give up when it comes to linux:
> 
> * https://github.com/LegendaryB/NeatInput (What I currently use)
> * https://github.com/Kir-Antipov/GlobalHook
> 
> If this sharp hook works I might be able to make it more compatible across platforms

Don't force yourself to do anything for linux since there SURELY will be other problems, and it seems like not so many people really want to use this on linux ;) But there are a lot of osu players who plays on linux because of lags on windows, so if you will rewrite it eventually it might be helpful for someone. I will be happy to help you!

**Comment by DjCrqss** [comment]
Sorry, been deplayed indefinitely due to personal things ;(. Will try do in the future!

**Comment by zmeyka3310** [comment]
this is pretty much dead, but doesnt wooting provide the analogsdk that works on linux too?

**Comment by YAUIO** [comment]
> this is pretty much dead, but doesnt wooting provide the analogsdk that works on linux too?

yes they do, but the application is written using windows forms, so it anyway needs a rewrite

**Comment by Sainan** [comment]
I've made an alternative server that also works on Linux: <https://github.com/Sainan/wootverlay-alt-server>

Imo, the hard part with this kind of thing on Linux is that there's no API to just grab the digital keyboard state, which I ended up solving by discovering the HID and parsing the input reports: <https://github.com/calamity-inc/Soup/blob/19cd6677984b5e9f4819c26cbc600d12999ea707/soup/DigitalKeyboard.cpp#L166-L195>

**Comment by YAUIO** [comment]
> I've made an alternative server that also works on Linux: https://github.com/Sainan/wootverlay-alt-server
> 
> Imo, the hard part with this kind of thing on Linux is that there's no API to just grab the digital keyboard state, which I ended up solving by discovering the HID and parsing the input reports: https://github.com/calamity-inc/Soup/blob/19cd6677984b5e9f4819c26cbc600d12999ea707/soup/DigitalKeyboard.cpp#L166-L195

Thank you! I think we can close the issue now idk
